### ISSUE TITLE
error: no image using camera 0 of platform 0

### ISSUE THREAD

**Issue by 945540968** [openMVG/openMVG#1148] opened 2017-11-14 12:32 UTC
After using SFM pipeline, we want to transform the output into openMVS. But we came across a problem like this:

C:\openMVS\build\openMVG\Windows-AMD64-Release\Debug>openMVG_main_openMVG2openMVS -i C:/openMVS/build/openMVG/software/SfM/test_result/matches/sfm_data.json -d C:/Users/lzj/Desktop/MVS -o C:/Users/lzj/Desktop/MVS/scene.mvs

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
error: no image using camera 0 of platform 0
Scene saved to OpenMVS interface format:
        22 images (0 calibrated)
        0 Landmarks

OMG! We have spent two weeks on solving the problem, can you help us? we'll be very grateful!

**Comment by pmoulon** [comment] 2017-11-14 17:03
The problem is that you are providing to the binary a sfm_data json that does not contains any camera poses.

the matches/sfm_data.json contains only the View and Intrinsic data.
Please use the sfm_data.bin that is stored in the SfM reconstruction directory (the one processed with Incremental or Global SfM)

**Comment by 945540968** [comment] 2017-11-15 02:49
Hi, pmoulon, thanks for your solution.  But when i use sfm_data.bin, the error still remains. Only the Landmarks increases from 0 to 2885. I'm looking forward to your reply.

C:\openMVS\build\openMVG\Windows-AMD64-Release\Debug>openMVG_main_openMVG2openMVS -i C:/openMVS/build/openMVG/software/SfM/test_result/reconstruction_global/sfm_data.bin -d C:/Users/lzj/Desktop/MVS -o C:/Users/lzj/Desktop/MVS/scene.mvs

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
error: no image using camera 0 of platform 0
Scene saved to OpenMVS interface format:
        22 images (0 calibrated)
        2885 Landmarks

**Comment by pmoulon** [comment] 2017-11-15 02:54
Can you share your sfm_data.bin file?

**Comment by 945540968** [comment] 2017-11-15 02:56
Of course, wait a minute please.

**Comment by 945540968** [comment] 2017-11-15 02:58
[sfm_data.zip](https://github.com/openMVG/openMVG/files/1473273/sfm_data.zip)

**Comment by pmoulon** [comment] 2017-11-15 03:22
After investigation I think it's because the images cannot be reached.

What I suggest you to do is the following:
- use full_path if you can.
Here a way to update the full_path for the image directory:
-> `openMVG_main_ConvertSfM_DataFormat -i sfm_data.bin -o sfm_data.json`
Then edit the field `"root_path": "test_image",` to have the full_path where your image is and run again openMVG_main_openMVG2openMVS on your updated `sfm_data.json`

I will update the binary with an error message to display that the image corresponding to the view is not accessible.

**Comment by pmoulon** [comment] 2017-11-15 03:32
The patch that will display you the appropriate message is now pushed to the `develop` branch.

**Comment by 945540968** [comment] 2017-11-15 04:09
Hi, pmoulon, thanks for your solution, but i can't understand all of what you said. My steps are as follows:
(I use `full_path` stands for `C:/openMVS/build/openMVG/software/SfM`, because it's too long)
1.  `python SfM_GlobalPipeline.py full_path/test_image full_path/test_result`
2. `openMVG_main_ConvertSfM_DataFormat -i full_path/test_result/reconstruction_global/sfm_data.bin -o full_path/test_result/matches/sfm_data.json`
3. `openMVG_main_openMVG2openMVS -i full_path/test_result/matches/sfm_data.json -d C:/MVS -o C:/MVS/scene.mvs`
And then, the program died here.
![problem](https://user-images.githubusercontent.com/33658092/32818185-c3ed4b80-c9fc-11e7-9f73-a7b591edc03b.png)


I have two questions as follows:
1. How can i "` edit the field "root_path": "test_image"`" as you said.
2. I see you just update the  src/software/SfM/main_openMVG2openMVS.cpp. Is that means i need compile the openMVG again?

I known maybe my questions is silly, Can you help me?.

**Comment by 945540968** [comment] 2017-11-15 04:19
As you say, lacking the full_path of test_image is the reason of my issue. But why the program run failed again after i use `python SfM_GlobalPipeline.py full_path/test_image full_path/test_result`?

**Comment by pmoulon** [comment] 2017-11-15 04:22
The pipeline should not fails with full_path.
Can you elaborate to tell me which part is not working?

On my computer I tried `python SfM_GlobalPipeline.py ./ImageDataset_SceauxCastle/images/ ./reconstruction_foo` and everything ran fine.

**Comment by 945540968** [comment] 2017-11-15 04:29
`python SfM_GlobalPipeline.py full_path/test_image full_path/test_result` run success.
but `openMVG_main_openMVG2openMVS -i full_path/test_result/matches/sfm_data.json -d C:/MVS -o C:/MVS/scene.mvs` run faild.  The progress bar is always 0%.

**Comment by pmoulon** [comment] 2017-11-15 04:33
Please, note that you did not use a sfm_data json that contain camera poses!
The `matches/sfm_data.json` contains only `Views` and `Intrinsics` information. 

Please use the sfm_data.bin produced in `full_path/test_result//reconstruction_global/sfm_data.bin`

**Comment by Datoow** [comment] 2017-11-15 04:45
WOW， I have got the same problem，willing to watch how to solve it....

**Comment by pmoulon** [comment] 2017-11-15 04:54
Please note that there is no problem:
1- Please use full path
2- Be sure that you are using a sfm_data that contains camera poses and structure (sfm_data.bin)

**Comment by 945540968** [comment] 2017-11-15 04:57
Now i run two program as follows:

![pic1](https://user-images.githubusercontent.com/33658092/32819364-db37b99a-ca03-11e7-9588-1b9a6f8a723f.png)



![pic2](https://user-images.githubusercontent.com/33658092/32819369-e0358634-ca03-11e7-8f4d-553c97a256df.png)


Now The progress bar is in 30% after spending 10 minute, is it normal?

**Comment by 945540968** [comment] 2017-11-15 05:01
Dear pmoulon, thanks for your patience. Thank you very much!!

**Comment by 945540968** [comment] 2017-11-15 05:01
This problem has been solved! :)

**Comment by pmoulon** [comment] 2017-11-15 05:20
Picture undistortion is not yet run in parallel but you can help on that ;-) 

Please, can you close the issue?

**Closed** 2017-11-15 05:31 UTC
Labels: question
