### ISSUE TITLE
[Question] Cropping Images

### ISSUE THREAD

**Issue by Rixikso** [openMVG/openMVG#1005] opened 2017-07-31 17:49 UTC
Recently I shoot some high quality photos in RAW format then I converted them to jpeg in lower resolution 3369x2249. Next performed sfm pipeline and reconstruction went awesome but Those photos were shot from too far away of the object and I received whole room were the reconstruction was made. 

So I thought that I will cropped those images (without loss of quality because of theirs high quality. Still 3369x2249) and the reconstruction will be more focused on the model. After MVG sfm reconstruction and exporting it to the MVS I saw that there's bunch of weirdly distorted images and bunch of black ones (not configured cameras) [MVS process exit with status non zero]

Is this possible to make it work or it's just an expected and cropped images can't be used in openMVG/openMVS pipeline

by cropped image I understand<- image with preserved aspect ratio and this peace of photo was centered on the model.

If someone could help I would be grateful :)

**Comment by rperrot** [comment] 2017-08-01 06:03
I think (one of) the issue is that cropping does change fov and EXIF is kept as it was before cropping. 

You should use masks on your images instead of crop. For that, you may define binary mask (white you keep data, black you mask) with name XXX_mask.png where XXX is the name of your image (without extension) in the folder of your images and openMVG will do the job.

**Comment by pmoulon** [comment] 2017-08-02 22:27
Using cropped image is not recommended since the resulting image will not respect the camera model (classic pinhole reprojection model). Often when you cropped you will mode the principal point position and so the initial guess will not work.

I would advise the same as @rperrot and use a mask as the feature computation stage.
Or you can also constraint the MVS point cloud to stay in a given area -> In OpenMVS you can cut/edit the mesh to the section you want and give it back as input for the later stage.

**Comment by Rixikso** [comment] 2017-08-04 15:46
I had already have implemented that stage where i filter OpenMVS pointcloud to the area of the interest. 
When I filtered it the output reconstruction came out very noisy. I will try it again maybe this set will be reconstructed differently. 
I will also try that masking approach. Thanks for your time :)

**Comment by pmoulon** [comment] 2017-08-04 16:12
Can we close the issue?

**Comment by Rixikso** [comment] 2017-08-04 16:16
Obviously you can but maybe my answer will help someone :D So I advise to wait for outcome of my reconstruction before closing this thread :)

**Comment by pmoulon** [comment] 2017-08-04 16:23
Ok, I let you add some additional info and let you close this issue later on ;-)

**Comment by Rixikso** [comment] 2017-08-08 19:52
Filtering in openMVS generates some noise objects near the object of interest and the reconstruction quality is slightly lower. 

OpenMVG masking
When Image Listing the image and masks I get this output:

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Warning & Error messages:
photo (1 of 102)_mask.png is a mask image
photo (100 of 102)_mask.png is a mask image
photo (101 of 102)_mask.png is a mask image
photo (102 of 102)_mask.png is a mask image
photo (11 of 102)_mask.png is a mask image
--------------------------------------------------
and so one
--------------------------------------------------
SfMInit_ImageListing report:
listed #File(s): 168
usable #File(s) listed in sfm_data: 102
usable #Intrinsic(s) listed in sfm_data: 21

After openMVG and openMVS I get the same mesh regardless of mask usage. Do you have any ideas why this is happening ?

MASK   
Dimensions: 3369 x 2246
Bit depth: 24
format: png

Photos
Dimensions: 3369 x 2246
Bit depth: 24
format: jpeg

**Comment by pmoulon** [comment] 2017-08-08 20:01
- Are you sure that the mask have been used by OpenMVS?

- Does the point cloud computed by OpenMVG is different if you are using or not the mask?

**Comment by Rixikso** [comment] 2017-08-08 22:10
(1) - I don't know if there were used. There's no mask images in working folder of openMVS. Is there a special option to use those masks with OpenMVS ?
(2) - I debugged scene point cloud (of openMVS) and number of points are roughly the same.

Any idea what I am doing wrong ?

**Comment by pmoulon** [comment] 2017-08-08 22:15
(1) Short answer [here](https://github.com/cdcseacave/openMVS/issues/144#issuecomment-261072232). Mask are supported but there is no interface to link image and mask yet from the command line.

(2) This question was about OpenMVG. I mean do you notice a difference in the produced point cloud -> clouds_and_poses.ply when you are using the mask or there is not mask in the image folder?

**Comment by Rixikso** [comment] 2017-08-09 07:44
(1) So I would have to add interface for it okey. I try to look into it.

(2) The produced point clouds are roughly the same for both cases with and without Masks in Image folder (this initial image folder with photo set)

**Comment by pmoulon** [comment] 2017-08-09 15:44
(2) Can you share your image dataset and masks?

**Comment by Rixikso** [comment] 2017-08-10 15:35
This is my set with mask link -> https://we.tl/yHTIdMYn3c

**Comment by pmoulon** [comment] 2017-08-10 17:35
Here the result of my experiment with your image:

I saw that the mask you are using cannot be opened by OpenMVG. I don't know why. I opened an image in Gimp and save it again in PNG and I was able to open it back in OpenMVG.
FYI the reading was failing [here](https://github.com/openMVG/openMVG/blob/master/src/openMVG/image/image_io.cpp#L265) for your image.

Once I saved again the png mask, the mask reading is ok and the feature filtering is ok
I.E for the image `photo (2 of 102).jpg`
![photo 2 of 102 _2544_](https://user-images.githubusercontent.com/3235050/29183369-42dd40b8-7db7-11e7-835e-1613e30db406.png)

- [ ] I will update main_ComputeFeatures to display an error message if the mask cannot be read.

--

Regarding your capture setting, I would advise you one more zoom level on the face.

**Comment by Rixikso** [comment] 2017-08-10 19:45
Really weird :D. 
Thanks for your information. 

I will try that with those masks and will see what I get from that.

**Comment by pmoulon** [comment] 2017-08-11 03:32
@Rixikso 
With the last push in develop, now if the mask is present and cannot be read, an error message is displayed and the feature extraction stops.

Thank you for your feedback that helped making `main_ComputeFeatures` more robust to invalid images (masks images that cannot be read). :+1:

**Comment by Rixikso** [comment] 2017-08-12 03:18
With masks the reconstruction went so much worse for one side of mesh. (but it halfed the execution time from 20 to 10 min). Meshes link -> https://we.tl/QVJxu5Rx1F

I wonder if I would use mask for openMVS it would turn out better any thoughts on that ?
Or maybe you have some advice on how to improve this mesh quality with some options ? 

Right now It's just plain defaults with setting ULTRA

**Comment by pmoulon** [comment] 2017-08-12 18:14
> I wonder if I would use mask for openMVS it would turn out better any thoughts on that ?
 it will only limit the reconstruction to the visual hull that your mask and camera defines.

- The SfM was not right for the scene with the mask (the loop closure on the head is not right). I would advise you to use Incremental SfM.

Did you use RefineMesh?

Else to improve the quality you need one more zoom level on the face in order to make more features detected for SfM and MVS.

You can see [here](http://3dcienciasaude.com.br/blog/?p=70) that @cogitas3d was able to reconstruct nice faces. You must be close to thefaceand make nice sharp looking picture. You can draw some points or lines on the face of your subject in order to make feature registration and MVS stage better.
![image](https://user-images.githubusercontent.com/3235050/29243255-c2080a96-7f9a-11e7-808f-1c42c691afe5.png)

**Comment by Rixikso** [comment] 2017-08-12 18:47
I am using incremental SFM and plain defaults with ULTRA setting 

I didn't use refine mesh because I don't need the mesh to be smooth but it should reconstruct the general shape of head plus I want shape of ears (It is crucial for my project). 

Also I didn't use it because it was very time consuming and I figure out that I will implement that step myself :P. This is what I get from different session link -> https://we.tl/gaUCYty0Sx
This is without Refine Mesh :) I tried to do it for it and it was about 6h. (Where openMVG + openMVS would take around 40 min without RefineMesh) 

Mesh which I received is fine without masks from that session but there's problem with this left ear. 

I will test this approach when I will find time for next photo session. Tell me what I understand is correct 
- shoot photos from closer range 
- don't brake the loop in the manner which I did in that session which you have seen

**Comment by pmoulon** [comment] 2017-08-12 19:02
Here my advice:
- Closer distance, picture as sharp as possible (tripod), don't hesitate to shoot a lot of pictures in order to help the feature tracking.
- Using a textured background (newspaper on the shoulder or the back)
- be sure to make a nice full loop (more that 360) in order to ensure coverage

If the texture is not crucial, make some drawing on the face.

**Comment by Rixikso** [comment] 2017-08-12 19:05
Okey thank you for your time and advices :)

I will now implement that masks feature for openMVS and will see if this will change anything for this reconstruction.

**Closed** 2017-11-10 03:37 UTC
Labels: question
