### ISSUE TITLE
How to use with OpenCV?

### ISSUE THREAD

**Issue by itsdsk** [openMVG/openMVG#872] opened 2017-04-15 15:25 UTC
I want to convert cv::Mat to openMVG::Image.

Is there a non-const openMVG::Image.getMat() that I could use in:

`cv::cv2eigen(cv::Mat, openMVG::Image.something())`

EDIT: To give a bit more info, the image source in my program is an openFrameworks ofImage, which I can convert to cv::Mat or get the unsigned char array of pixels directly.

So basically what I'm looking for is an internal (not from a file) interface to set openMVG images

**Comment by pmoulon** [comment] 2017-04-16 16:12
Hi @itsdsk 
The following must work
```
        cv::Mat image_cv;
        image_cv = cv::imread( sView_filename, CV_LOAD_IMAGE_GRAYSCALE );
        Image<uint8_t> image_openmvg;
        cv::cv2eigen(image_cv, *(Image<uint8_t>::Base*)&image_openmvg);
```

**Comment by itsdsk** [comment] 2017-04-18 16:39
Thanks! Worked exactly how you said with a resize function - never would've figured that out myself
```
    cv::Mat cv_image;
    ....
    Image<uint8_t> mvg_image;
    mvg_image.resize(cv_image.cols, cv_image.rows);
    cv::cv2eigen(cv_image, *(Image<uint8_t>::Base*)&mvg_image);
```

**Comment by pmoulon** [comment] 2017-04-18 16:41
Please close the issue if you don't have other point(s) to comment.

**Closed** 2017-04-18 16:45 UTC

**Comment by IdoMa** [comment] 2019-01-27 13:15
Just stating the obvious, but for that to work the `cv::Mat` object has to have `CV_8UC1` as its scalar type.

**Comment by a-mohsen** [comment] 2020-06-15 04:23
What if I want to use it with RGB image ?

**Comment by rperrot** [comment] 2020-06-15 05:36
@a-mohsen 

Please open a new issue since the thread you opened is more than 1 year old and your question is not directly related to this issue (and may be interesting for the community).

**Comment by fengweichangzi** [comment] 2021-07-08 08:48
Awesome work! I tried those codes but got the size error assert. I found the problem is from the begining  "CV_DbgAssert(src.rows == _rows && src.cols == _cols); " in cv2eigen function.  It seemed that using "cv::cv2eigen(cv_image, *(Image<uint8_t>::Base*)&mvg_image);" made output _rows = -1 and _cols=-1. It looked quite weird.

**Comment by pmoulon** [comment] 2021-07-08 19:44
@fengweichangzi can you share the code you use so we could repro on our side and see what is wrong?

**Comment by fengweichangzi** [comment] 2021-07-09 02:23
Thanks. It is quite simple.
`int main()
{
	// cv Mat -> mvg Image
	cv::Mat img_cv = cv::imread("building.jpg", cv::IMREAD_GRAYSCALE);

	Image<uint8_t> img_mvg;
	img_mvg.resize(img_cv.cols, img_cv.rows);

	// convert and save
	cv::cv2eigen(img_cv, *(Image<uint8_t>::Base*) & img_mvg);
	WriteImage("building_mvg.jpg", img_mvg);
}`

When debug, I got this error `OpenCV(4.5.1) Error: Assertion failed (src.rows == _rows && src.cols == _cols) in cv::cv2eigen, file D:\opencv\451\include\opencv2\core\eigen.hpp, line 222`

The problem is from here
`template<typename _Tp, int _rows, int _cols, int _options, int _maxRows, int _maxCols> static inline
void cv2eigen( const Mat& src,
               Eigen::Matrix<_Tp, _rows, _cols, _options, _maxRows, _maxCols>& dst )
{
    CV_DbgAssert(src.rows == _rows && src.cols == _cols);`

I used OpenCV 4.5.1 but it should not be with its version?
