### ISSUE TITLE
"Invalid input image graph for global SfM"...not enough features in images?

### ISSUE THREAD

**Issue by hotmeatballsoup** [openMVG/openMVG#657] opened 2016-10-23 14:17 UTC
I ran a set of photos of my living room table through an OpenMVG pipeline, and it resulted with Global SfM failing with a `Invalid input image graph for global SfM` message. I _believe_ this has to do with the photos I'm using, because my living room table and the floor have virtually identical textures.

The _exact_ commands I ran, along with their output are [here in this gist](https://gist.github.com/hotmeatballsoup/c5688cd9c759dbca87ae375c33bcf187).

[This repo here](https://github.com/hotmeatballsoup/3drecon-troubleshooting) shows the photos I used (under `/frames`) as well as the output from running the various OpenMVG tool (under `/matches`).

Can anyone spot anything in the photos, commands or outputs that provide clues as to why Global SfM failed? I had a problem the other day with a different set of photos, but using the `-p ULTRA` command on `ComputeFeatures` fixed that. **As you can see in the gist, I used `-p ULTRA` with these new photos and the problem is still presenting itself.** Any ideas? Thanks in advance!

**Comment by mitjap** [comment] 2016-10-26 11:23
My first though is that you should use more images if you are doing 360 of the table. The problem is not the texture (i think) but too huge angle change between images. Try with 30-40 images and I'm sure you will be successful. Then you can experiment what is the minimum number of images for your scene.

**Comment by pmoulon** [comment] 2016-10-26 16:10
I agree with @mitjap you need to check your photos coverage.

**Comment by zharvey-welltok** [comment] 2016-10-27 11:03
Thanks both @mitjap and @pmoulon - I will give it a try tonight.

I'm really trying to learn this tool and understand how it works - may I ask (either of you) what makes you think its simply a lack of images (or, too huge of an angle in between images)?

Is there something in the stdout that you saw in the gist? Or just basing this recommendation off of experience with OpenMVG?

Is there a way to have an OpenMVG binary run in "debug" or "verbose" mode, where it will give a reason for *why* SfM fails? I guess I'm just looking to understand how I can self-diagnose these issues in the future, and not have to bother you here with an issue each time something unexpected happens! :-)

Thanks again for the recommendation, like I said, I'll give it a try ASAP.

**Comment by pmoulon** [comment] 2016-10-27 23:04
I and @mitjap took a fast look to the picture and we saw that the overlap is not very large.

If you have graphviz installed, OpenMVG will log some image connectivity graph and so you will be able to diagnose yourself if your image collection is giving a single connected component or not (according the feature and matches settings).

**Comment by pmoulon** [comment] 2016-10-28 14:45
Just install graphviz and relaunch the computematches binaries graph will be computed and exported.
Perhaps you will need to force recomputation or to remove old computed data.

**Comment by zharvey-welltok** [comment] 2016-10-31 10:21
Thanks @pmoulon, I was seeing a lot of "no neato found" messages showing up in the console output, and now I know what they mean (looks like `neato` is a tool that lives inside the graphviz suite).

Please remember that I am new to all of this, including graphviz. It sounds like `main_ComputeMatches` will generate (as output) several `matches.X.bin` files. Are these the files I want to load into graphviz? Or are you saying that the mere existence of graphviz/neato being installed on the system will prompt `main_ComputeMatches` to export graphs?

I ask because my local setup is actually a little unorthodox:

* I have Mac laptop (host), with graphviz installed on it
* I have an Ubuntu 14.04 VM (well, actually a Vagrant box) with ffmpeg, OpenMVG, MVE and mvs-texturing installed on it

I have this setup because I found several other binaries (not OpenMVG!) extremely difficult to compile and/or work on my Mac.

So, I guess I'm asking: is there a way to export `main_ComputeMatches` output into graphviz manually?

**Comment by pmoulon** [comment] 2016-11-02 00:11
If you have graphviz in your path you can:
- relaunch and the graph will be computed
- or launch by hand graphviz:
  - see here the used command line https://github.com/openMVG/openMVG/blob/944254c65691b3b7c5fe54d5bdbe312c90de252f/src/openMVG/graph/graph_graphviz_export.hpp#L165

```neato -Tsvg -O -Goverlap=scale -Gsplines=false YOURDOTFILE```

**Comment by zharvey-welltok** [comment] 2016-11-03 00:24
OK, I got a *little* bit further here @pmoulon, thanks again for the help on this.

So I ran `openMVG_main_SfMInit_ImageListing`, then `openMVG_main_ComputeFeatures` and then finally `openMVG_main_ComputeMatches` on a set of images. This produced a `matches/putative_matches` file that I *believe* is what I need to use instead of the `YOURDOTFILE` in your code snippet above.

So I then manually ran `neato` on this `putative_matches` file like so:

    neato -Tsvg -O -Goverlap=scale -Gsplines=false putative_matches

And this produced a `putative_match.svg` file in the same directory.

I've never worked with SVG files before, so I'm not sure what kind of data they contain, or what kind of tool can open and work with them. Remember, I'm trying to use this so that I can diagnose why SfM is failing. And, in this particular case, I wasn't using enough images to begin with.

I found a tool called [ZGRViewer](http://zvtm.sourceforge.net/zgrviewer.html) that claims to be able to read SVG files, so I tried using that but had no luck.

So I ask: **Did I run the `neato` command on the correct file (`putative_matches`), and what do I do with the resulting SVG to diagnose SfM failures?** Thanks again!

**Comment by pmoulon** [comment] 2016-11-03 03:50
1. SVG viewing:
  -  you can use Inkscape, Chrome, Firefox ...

2. Matches graph
  - please consider the geometric_matches graph since it is the graph that will be considered for the SfM step
  - the putatives_matches graph is often dense since there is false matches between the image pairs

I agree that perhaps logging some info about the final geometric graph could be a good idea. Some info like:
- number of connected components
- mean node degree level
- ...

**Comment by zharvey-welltok** [comment] 2016-11-03 08:58
Thanks! So I took your advice and ran `neato` on `geometric_matches`, and then opened the resulting SVG:

![geometric_matches](https://i.imgsafe.org/afa9d8a814.png)

Boom! I *think* that this is what you have been talking about. No nodes connect to any other nodes. Some questions about this graph:

1. I assume each node represents a view/input image?
2. If there are no lines between two nodes, that means they don't share any matches?
3. So then, I assume that because my graph above has *no* lines connecting *any* nodes, that OpenMVG wasn't able to find a single match between any of my images?
4. How many matches (lines connecting nodes) are typically required in order for SfM (Global or Incremental) to work? Is there a typical ratio of nodes to edges that must be present? I guess I'm looking for some way to look at a graph like this and diagnose whether enough matches were made or not.

As for your comment about logging graph info, I have written it down on my list of TODOs, and expect I'll be submitting a PR at some point in the next 3 - 4 weeks. Thanks again for the hand-holding on this one!

**Comment by pmoulon** [comment] 2016-11-04 02:39
1. Yes, each image is representing a view (an image)
2. You're right
3. It means that OpenMVG did not find geometric coherent matches
4. For incremental SfM having 2 edges per nodes is sufficient o-o-o-o-o
   For global SfM triplet are required
```
o---o--o
 \o/ \o/
```

5. the size is not informative. The size just change depending of the length of the string inside it.

On my side I obtained some matches, see the geometrica djacency matrix
![geometricadjacencymatrix](https://cloud.githubusercontent.com/assets/3235050/19992663/17cccc36-a1fd-11e6-8136-acf078977096.png)

**Comment by zharvey-welltok** [comment] 2016-11-04 02:41
Awesome, thanks for all the help with this! I get it now! 👍

**Comment by pmoulon** [comment] 2016-11-23 04:18
@hotmeatballsoup I close the issue since the community provide feedback about it.

**Closed by pmoulon** 2016-11-23 04:18 UTC
Labels: question
