### ISSUE TITLE
openMVG_test_features does not compile on msvc2015 32bit

### ISSUE THREAD

**Issue by zwn** [openMVG/openMVG#859] opened 2017-04-08 15:24 UTC
It reports

```
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xutility(2371): error C2719: '_First': formal parameter with requested alignment of 32 won't be aligned
1>  R:\openMVG\src\openMVG/features/descriptor.hpp(138): note: see reference to function template instantiation '_OutIt std::copy<std::istream_iterator<openMVG::features::Descriptor<float,128>,char,std::char_traits<char>,ptrdiff_t>,std::back_insert_iterator<DescriptorsT>>(_InIt,_InIt,_OutIt)' being compiled
1>          with
1>          [
1>              _OutIt=std::back_insert_iterator<Descs_T>,
1>              DescriptorsT=Descs_T,
1>              _InIt=std::istream_iterator<openMVG::features::Descriptor<float,128>,char,std::char_traits<char>,ptrdiff_t>
1>          ]
1>  R:\openMVG\src\openMVG\features\features_test.cpp(48): note: see reference to function template instantiation 'bool openMVG::features::loadDescsFromFile<Descs_T>(const std::string &,DescriptorsT &)' being compiled
1>          with
1>          [
1>              DescriptorsT=Descs_T
1>          ]
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xutility(2371): error C2719: '_Last': formal parameter with requested alignment of 32 won't be aligned
```
So it knows alignment of 32 has been requested but it just reports it will not be done. I believe some more eigen allocator magic is needed here.

I had more problems before 1b1816f022b3ae4437be8b5939759b36600570be but now, this seems to be the last one. All other tests pass in both 32 an 64bit modes.

**Comment by pmoulon** [comment] 2017-04-08 15:28
Which branch did you test?

I made some change yesterday in the WIP branch called develop_cpu_capabilitieshttps://github.com/openMVG/openMVG/commit/1b1816f022b3ae4437be8b5939759b36600570be

**Comment by zwn** [comment] 2017-04-08 15:30
Current develop: ee9b73e1464552b289faa4c3d90c8699fb7498f3

The commit you are mentioning 1b1816f022b3ae4437be8b5939759b36600570be fixed some other problems (mainly segfaults with 64bit build). This one remains.

**Comment by pmoulon** [comment] 2017-04-08 15:31
Was ok for me on Visual Studio 2015 (all test was running).
Can you tell me if this one remains for you in 32 or in 64 bit build?

Can you track the calle that cause the error?

**Comment by pmoulon** [comment] 2017-04-08 15:52
I re-tested in 64bit (release and debug) and it works for me.

**Comment by zwn** [comment] 2017-04-08 17:44
The problem is with 32bit build (I tried to note that in the issue name and initial description). The 64bit build works for me too.

**Comment by pmoulon** [comment] 2017-04-08 19:32
Will try to investigate. Thx

**Comment by pmoulon** [comment] 2017-04-09 03:42
I found a fix consisting in changing the std::copy into a single loop (weird Visual Studio bug).
I changed also a bit the serialization in order to allocate less temporary memory, we can certainly do better and directly use `archive(cereal::binary_data(this->data(), N * sizeof(T)));` but I did not succeed to use it.

@bjornpiltz Have you some experiment with `cereal::binary_data` everytime I try to use it I got the message (due to inheritance, I did not succeed to use specialize in the right way with the template class):
```
Types must either have a serialize function, load/save pair, or load_minimal/save_minimal pair (you may not mix these). 
 Serialize functions generally have the following signature: 

 template<class Archive> 
   void serialize(Archive & ar) 
   { 
     ar( member1, member2, member3 ); 
   } 
```

**Comment by pmoulon** [comment] 2017-04-09 03:56
@zwn Can you test the branch develop_visual_studio_alignment32bit.
The problem must be solved.

**Comment by zwn** [comment] 2017-04-10 09:06
I can compile and successfully run all tests in the branch develop_visual_studio_alignment32bit using both 32bit and 64bit! I think it is good to go.

**Comment by bjornpiltz** [comment] 2017-04-10 09:14
It compiles for me as well. There seems to be a problem with 'std::istream_iterator' and alignment.

**Comment by bjornpiltz** [comment] 2017-04-10 09:14
Which project do I have to compile to test Descriptor::save() and Descriptor::load()?

**Comment by pmoulon** [comment] 2017-04-10 15:56
@bjornpiltz  => main_ComputeFeatures

**Comment by bjornpiltz** [comment] 2017-04-10 18:51
Ok, I got the same error you did, but only for Archive=json|xml. This might be by design, as it's unclear what a text based format should do with a binary blob - encode base64? [http://stackoverflow.com/a/27749324](This SO post) seems to suggest this.

**Comment by pmoulon** [comment] 2017-04-10 19:55
Seems like we have to use some traits if we want to go further:
Traits to test if the serialization is binary or text...
https://github.com/USCiLab/cereal/pull/184/files#diff-a7d0b36e999b7dc66af8b95f9c1d23e1R47

**Comment by pmoulon** [comment] 2017-04-12 06:03
Compilation fix now merged in develop.
Thank you @zwn for your help on this.

**Closed by pmoulon** 2017-04-12 06:03 UTC
