### ISSUE TITLE
build ui [QT]

### ISSUE THREAD

**Issue by lujun2445** [openMVG/openMVG#446] opened 2016-01-04 17:26 UTC
Hello:
I want to build ui control_points_registration in windows, I installed qt-opensource-windows-x86-vs2010-4.8.6, and vs2013, and get an error:
  2>------ Build started: Project: ui_openMVG_control_points_registration, Configuration: Debug x64 ----  --
2>QtGuid4.lib(QtGuid4.dll) : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64' 
I found ui surport qt4 only, but qt4 is not of  type 'x64', what should I do?
thanks very much!

**Comment by pmoulon** [comment] 2016-01-04 17:46
I think it's because you need to have qt-opensource compiled in 64bit.
You can compile it yourself in x64 on your computer. It will take some time.

**Comment by lujun2445** [comment] 2016-01-05 15:03
Thanks  for the reply! 
I have compiled qt4 in 64bit and the ui works well! But I think maybe a BA with GCP is needed after geo registration, which is always done in photogrammetry.
Thanks a lot!

**Comment by pmoulon** [comment] 2016-01-05 15:27
The BA with GPC is already planned for V1.0
See https://github.com/openMVG/openMVG/issues/398
The problem is that we don't know in advance if we want to weight more the GPC or the Tiepoint.

**Comment by lujun2445** [comment] 2016-01-19 14:31
In photogrammetry the  weight of the GPC is offen set to 4, and the  weight of the Tiepoint is offen set to 1.

**Comment by pmoulon** [comment] 2016-01-19 15:15
By "often" do you think at typical values used in other software or to some paper references?

**Comment by lujun2445** [comment] 2016-01-19 15:29
This is a empirical value, and in our project it is relatively robust than some method of changing weights in iterative process, I am trying to find some references.

**Comment by pmoulon** [comment] 2016-01-19 15:30
We can think to make this value an option (set by default to 4).

**Comment by lujun2445** [comment] 2016-01-19 15:36
OK, thanks and I will find some paper references about this.

**Comment by pmoulon** [comment] 2016-01-29 13:15
@lujun2445 I close the issue since the UI issue is solved.
We can continue still the discussion about GCP in #398 if you want.

**Closed by pmoulon** 2016-01-29 13:15 UTC
Labels: build
