### ISSUE TITLE
[SfM] No initial pair displayed in IncrementalSfM if missing k or f 

### ISSUE THREAD

**Issue by lailazouaki** [openMVG/openMVG#337] opened 2015-07-09 13:04 UTC
Hi,

I used some jpeg without EXIF in IncrementalSfM method.
I did : 
- openMVG_main_SfMInit_ImageListing but I forgot to specify either f or k
- openMVG_main_ComputeFeatures with -p HIGH
- openMVG_main_ComputeMatches 
- openMVG_main_IncrementalSfM

When it came to choose manually a initial pair : 
 
 "Pairs that have valid intrinsic and high support of points are displayed:
 Choose one pair manually by typing the two integer indexes"

i.e no pair was displayed. 
In sequential_SfM.cpp, i checked : 
- map_Matches.size !=0 
- but  vec_NbMatchesPerPair.size = 0

However, when i do specify -f, everything works fine. Maybe there should be an error message to explain why no pair is displayed.

Thanks,

**Comment by pmoulon** [comment] 2015-07-09 13:39
Thanks for the feedback,
I not this issue as a required enhancement and I will do something for it for OpenMVG 0.9.

**Comment by pmoulon** [comment] 2015-07-19 07:04
@lailazouaki The problem is now fixed in the develop branch and will be pushed in master when openMVG v0.9 will be ready

**Closed by pmoulon** 2015-07-19 07:04 UTC
Labels: enhancement
