### ISSUE TITLE
algorithm.h internal compiler error

### ISSUE THREAD

**Issue by cenit** [openMVG/openMVG#1765] opened 2020-06-30 14:52 UTC
very similar to #1667, but I cannot solve the problem.
When building OpenMVG, if enabling OpenMP, I encounter an error at `kvld.cpp`. Without OpenMP, everything is fine.

```
[45/125] C:\PROGRA~2\MICROS~1\2019\BUILDT~1\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe   /TP -DOPENMVG_USE_OPENMP -D__AVX2__ -D__AVX__ -D__BMI2__ -D__FMA__ -D__SSE2__ -D__SSE3__ -D__SSE4_1__ -D__SSE4_2__ -D__SSSE3__ -IC:\src\vcpkg\installed\x64-windows\include\eigen3 -IC:\src\vcpkg\buildtrees\openmvg\src\0bf42262fc-cf724333d8\src -IC:\src\vcpkg\installed\x64-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /arch:AVX2 -openmp /MD /O2 /Oi /Gy /DNDEBUG /Z7    /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP /arch:AVX2 -openmp -D_USE_MATH_DEFINES -DNOMINMAX /showIncludes /FoopenMVG\matching\kvld\CMakeFiles\openMVG_kvld.dir\kvld.cpp.obj /FdopenMVG\matching\kvld\CMakeFiles\openMVG_kvld.dir\openMVG_kvld.pdb /FS -c C:\src\vcpkg\buildtrees\openmvg\src\0bf42262fc-cf724333d8\src\openMVG\matching\kvld\kvld.cpp
FAILED: openMVG/matching/kvld/CMakeFiles/openMVG_kvld.dir/kvld.cpp.obj 
C:\PROGRA~2\MICROS~1\2019\BUILDT~1\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe   /TP -DOPENMVG_USE_OPENMP -D__AVX2__ -D__AVX__ -D__BMI2__ -D__FMA__ -D__SSE2__ -D__SSE3__ -D__SSE4_1__ -D__SSE4_2__ -D__SSSE3__ -IC:\src\vcpkg\installed\x64-windows\include\eigen3 -IC:\src\vcpkg\buildtrees\openmvg\src\0bf42262fc-cf724333d8\src -IC:\src\vcpkg\installed\x64-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /arch:AVX2 -openmp /MD /O2 /Oi /Gy /DNDEBUG /Z7    /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP /arch:AVX2 -openmp -D_USE_MATH_DEFINES -DNOMINMAX /showIncludes /FoopenMVG\matching\kvld\CMakeFiles\openMVG_kvld.dir\kvld.cpp.obj /FdopenMVG\matching\kvld\CMakeFiles\openMVG_kvld.dir\openMVG_kvld.pdb /FS -c C:\src\vcpkg\buildtrees\openmvg\src\0bf42262fc-cf724333d8\src\openMVG\matching\kvld\kvld.cpp
C:\src\vcpkg\buildtrees\openmvg\src\0bf42262fc-cf724333d8\src\openMVG/matching/kvld/algorithm.h(56): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
C:\src\vcpkg\buildtrees\openmvg\src\0bf42262fc-cf724333d8\src\openMVG/matching/kvld/algorithm.h(56): warning C4244: 'initializing': conversion from 'double' to 'const int', possible loss of data
C:\src\vcpkg\buildtrees\openmvg\src\0bf42262fc-cf724333d8\src\openMVG/matching/kvld/algorithm.h(57): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
C:\src\vcpkg\buildtrees\openmvg\src\0bf42262fc-cf724333d8\src\openMVG/matching/kvld/algorithm.h(57): warning C4244: 'initializing': conversion from 'double' to 'const int', possible loss of data
C:\src\vcpkg\buildtrees\openmvg\src\0bf42262fc-cf724333d8\src\openMVG/matching/kvld/algorithm.h(101): warning C4305: '=': truncation from 'double' to 'float'
C:\src\vcpkg\buildtrees\openmvg\src\0bf42262fc-cf724333d8\src\openMVG/matching/kvld/algorithm.h(103): warning C4305: '=': truncation from 'double' to 'float'
C:\src\vcpkg\buildtrees\openmvg\src\0bf42262fc-cf724333d8\src\openMVG/matching/kvld/algorithm.h(107): warning C4305: '+=': truncation from 'double' to 'float'
C:\src\vcpkg\buildtrees\openmvg\src\0bf42262fc-cf724333d8\src\openMVG/matching/kvld/algorithm.h(109): warning C4305: '+=': truncation from 'double' to 'float'
C:\src\vcpkg\buildtrees\openmvg\src\0bf42262fc-cf724333d8\src\openMVG/matching/kvld/algorithm.h(111): warning C4305: '-=': truncation from 'double' to 'float'
C:\src\vcpkg\buildtrees\openmvg\src\0bf42262fc-cf724333d8\src\openMVG/matching/kvld/kvld.h(44): warning C4305: 'initializing': truncation from 'double' to 'float'
C:\src\vcpkg\buildtrees\openmvg\src\0bf42262fc-cf724333d8\src\openMVG\matching\kvld\kvld.cpp(50): warning C4244: '=': conversion from 'double' to 'T', possible loss of data
        with
        [
            T=float
        ]
C:\src\vcpkg\buildtrees\openmvg\src\0bf42262fc-cf724333d8\src\openMVG\matching\kvld\kvld.cpp(215): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
C:\src\vcpkg\buildtrees\openmvg\src\0bf42262fc-cf724333d8\src\openMVG\matching\kvld\kvld.cpp(216): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
C:\src\vcpkg\buildtrees\openmvg\src\0bf42262fc-cf724333d8\src\openMVG\matching\kvld\algorithm.h(107) : fatal error C1001: Internal compiler error.
(compiler file 'd:\agent\_work\2\s\src\vctools\Compiler\Utc\src\p2\main.c', line 181)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information

ninja: build stopped: subcommand failed.
```

Visual Studio 2019, v16.6.2 (latest version as of now)

**Comment by pmoulon** [comment] 2020-07-03 01:38
Could be due to the last version of the compiler.
What I would recommend to you, for the time being, is to remove the KVLD folder from the make configuration (by removing the `kvld` folder).
I will try to see if I can setup the last VS on a machine and reproduce this behavior

**Comment by rwiesenfarth** [comment] 2020-07-06 18:16
Got the same issue with Visual Studio 16.6.3 / Visual C++ 2019.
I could avoid the internal compiler error by introducing a local variable `ang`:

```
inline bool anglefrom( float x, float y, float& angle )
{
  float ang = 0.f;

  if (x != 0.f )
    ang = atan( y / x );
  else if (x > 0)
    ang = atan( y / x );
  else if (y > 0)
    ang = PI_ / 2;
  else if (y < 0)
    ang =- PI_ / 2;
  else return false;

  if (x < 0.f )
    ang += PI_;
  while ( ang < 0.f)
    ang += 2 * PI_;
  while ( ang >= 2 * PI_)
    ang -= 2 * PI_;
  assert( ang >= 0.f && ang < 2 * PI_ );
  angle = ang;
  return true;
}
```

**Comment by pmoulon** [comment] 2020-07-15 13:32
Thank you @rwiesenfarth @cenit I will tag the issue for the next OpenMVG version

**Comment by lexvandersluijs** [comment] 2020-09-25 10:26
I found a second workaround for this issue: go to Properties of kvld.cpp -> C/C++ -> Optimization and disable optimization. Maybe this helps in case the fix above stops working after a compiler update.

**Comment by pmoulon** [comment] 2020-10-20 23:05
Issue is now fixed. Thx you @lexvandersluijs @cenit @JohnMath3w

**Closed by pmoulon** 2020-10-20 23:05 UTC
Labels: build
