### ISSUE TITLE
a problem Using OpenMVG as a third party library dependency in CMake

### ISSUE THREAD

**Issue by StringShannon** [openMVG/openMVG#1144] opened 2017-11-11 12:21 UTC
Hi @ pmoulon , I have a question about Compiling myself code using OpenMVG as a third party library dependency in CMake. the problem occured, when I use functions in class OpenMVG::features.
system - Ubuntu16.04
the compiled code is /src/openMVG/features_image_matching
-----------------------------------------------------------------------------------------------------
- my CMakeList.txt :
```
cmake_minimum_required( VERSION 3.5 )
SET( CMAKE_C_FLAGS_RELEASE "$ENV{CXXFLAGS} -O1 -Wall " )
project(study_mvg)
set( CMAKE_CXX_STANDARD 11 )
# OpenMVG
set( CMAKE_PREFIX_PATH "/home/jarvis/CV/openmvg/share/openMVG/cmake/" )
find_package( OpenMVG REQUIRED )
include_directories( ${OPENMVG_INCLUDE_DIRS} )
add_executable( main main.cpp )
target_link_libraries( main ${OPENMVG_LIBRARIES} )
```
-----------------------------------------------------------------------------------------------------------
- the information of cmake :
```
/home/jarvis/Code/c++/study_mvg/build> make -j2
-- ----
-- OpenMVG Find_Package
-- ----
-- Found OpenMVG version: 1.2.0
-- Installed in: /home/jarvis/CV/openmvg
-- Used OpenMVG libraries: openMVG_image;openMVG_features;openMVG_geometry;openMVG_matching;openMVG_matching_image_collection;openMVG_kvld;openMVG_multiview;openMVG_lInftyComputerVision;openMVG_system;openMVG_sfm
-- Required CFLAGS: -DOPENMVG_USE_AVX2;-DOPENMVG_USE_OPENMP
-- ----
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jarvis/Code/c++/study_mvg/build
[ 50%] Building CXX object CMakeFiles/main.dir/main.cpp.o
In file included from /home/jarvis/CV/openmvg/include/openMVG/matching/metric.hpp:12:0,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/binary_regions.hpp:16,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/regions_factory.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp:57,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:4:
/home/jarvis/CV/openmvg/include/openMVG/matching/metric_avx2.hpp: In function ‘int openMVG::matching::L2_AVX2(const uint8_t*, const uint8_t*, std::size_t)’:
/home/jarvis/CV/openmvg/include/openMVG/matching/metric_avx2.hpp:41:38: warning: AVX vector return without AVX enabled changes the ABI [-Wpsabi]
   __m256i acc (_mm256_setzero_si256());
                                      ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:41:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Core:269,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Dense:1,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_container.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_io.hpp:12,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/5/include/avxintrin.h:1209:1: error: inlining failed in call to always_inline ‘__m256i _mm256_setzero_si256()’: target specific option mismatch
 _mm256_setzero_si256 (void)
 ^
In file included from /home/jarvis/CV/openmvg/include/openMVG/matching/metric.hpp:12:0,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/binary_regions.hpp:16,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/regions_factory.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp:57,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:4:
/home/jarvis/CV/openmvg/include/openMVG/matching/metric_avx2.hpp:41:38: error: called from here
   __m256i acc (_mm256_setzero_si256());
                                      ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:43:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Core:269,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Dense:1,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_container.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_io.hpp:12,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx2intrin.h:119:1: error: inlining failed in call to always_inline ‘__m256i _mm256_add_epi32(__m256i, __m256i)’: target specific option mismatch
 _mm256_add_epi32 (__m256i __A, __m256i __B)
 ^
In file included from /home/jarvis/CV/openmvg/include/openMVG/matching/metric.hpp:12:0,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/binary_regions.hpp:16,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/regions_factory.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp:57,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:4:
/home/jarvis/CV/openmvg/include/openMVG/matching/metric_avx2.hpp:59:58: error: called from here
     acc = _mm256_add_epi32(acc, _mm256_add_epi32(dl, dh));
                                                          ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:43:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Core:269,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Dense:1,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_container.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_io.hpp:12,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx2intrin.h:119:1: error: inlining failed in call to always_inline ‘__m256i _mm256_add_epi32(__m256i, __m256i)’: target specific option mismatch
 _mm256_add_epi32 (__m256i __A, __m256i __B)
 ^
In file included from /home/jarvis/CV/openmvg/include/openMVG/matching/metric.hpp:12:0,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/binary_regions.hpp:16,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/regions_factory.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp:57,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:4:
/home/jarvis/CV/openmvg/include/openMVG/matching/metric_avx2.hpp:59:27: error: called from here
     acc = _mm256_add_epi32(acc, _mm256_add_epi32(dl, dh));
                           ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:43:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Core:269,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Dense:1,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_container.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_io.hpp:12,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx2intrin.h:341:1: error: inlining failed in call to always_inline ‘__m256i _mm256_madd_epi16(__m256i, __m256i)’: target specific option mismatch
 _mm256_madd_epi16 (__m256i __A, __m256i __B)
 ^
In file included from /home/jarvis/CV/openmvg/include/openMVG/matching/metric.hpp:12:0,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/binary_regions.hpp:16,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/regions_factory.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp:57,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:4:
/home/jarvis/CV/openmvg/include/openMVG/matching/metric_avx2.hpp:58:35: error: called from here
     dh = _mm256_madd_epi16(dh, dh);
                                   ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:43:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Core:269,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Dense:1,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_container.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_io.hpp:12,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx2intrin.h:857:1: error: inlining failed in call to always_inline ‘__m256i _mm256_unpackhi_epi8(__m256i, __m256i)’: target specific option mismatch
 _mm256_unpackhi_epi8 (__m256i __A, __m256i __B)
 ^
In file included from /home/jarvis/CV/openmvg/include/openMVG/matching/metric.hpp:12:0,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/binary_regions.hpp:16,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/regions_factory.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp:57,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:4:
/home/jarvis/CV/openmvg/include/openMVG/matching/metric_avx2.hpp:57:64: error: called from here
     __m256i dh = _mm256_unpackhi_epi8(d, _mm256_setzero_si256());
                                                                ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:41:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Core:269,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Dense:1,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_container.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_io.hpp:12,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/5/include/avxintrin.h:1209:1: error: inlining failed in call to always_inline ‘__m256i _mm256_setzero_si256()’: target specific option mismatch
 _mm256_setzero_si256 (void)
 ^
In file included from /home/jarvis/CV/openmvg/include/openMVG/matching/metric.hpp:12:0,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/binary_regions.hpp:16,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/regions_factory.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp:57,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:4:
/home/jarvis/CV/openmvg/include/openMVG/matching/metric_avx2.hpp:57:38: error: called from here
     __m256i dh = _mm256_unpackhi_epi8(d, _mm256_setzero_si256());
                                      ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:43:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Core:269,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Dense:1,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_container.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_io.hpp:12,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx2intrin.h:341:1: error: inlining failed in call to always_inline ‘__m256i _mm256_madd_epi16(__m256i, __m256i)’: target specific option mismatch
 _mm256_madd_epi16 (__m256i __A, __m256i __B)
 ^
In file included from /home/jarvis/CV/openmvg/include/openMVG/matching/metric.hpp:12:0,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/binary_regions.hpp:16,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/regions_factory.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp:57,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:4:
/home/jarvis/CV/openmvg/include/openMVG/matching/metric_avx2.hpp:55:35: error: called from here
     dl = _mm256_madd_epi16(dl, dl);
                                   ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:43:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Core:269,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Dense:1,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_container.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_io.hpp:12,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx2intrin.h:885:1: error: inlining failed in call to always_inline ‘__m256i _mm256_unpacklo_epi8(__m256i, __m256i)’: target specific option mismatch
 _mm256_unpacklo_epi8 (__m256i __A, __m256i __B)
 ^
In file included from /home/jarvis/CV/openmvg/include/openMVG/matching/metric.hpp:12:0,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/binary_regions.hpp:16,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/regions_factory.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp:57,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:4:
/home/jarvis/CV/openmvg/include/openMVG/matching/metric_avx2.hpp:54:64: error: called from here
     __m256i dl = _mm256_unpacklo_epi8(d, _mm256_setzero_si256());
                                                                ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:41:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Core:269,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Dense:1,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_container.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_io.hpp:12,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/5/include/avxintrin.h:1209:1: error: inlining failed in call to always_inline ‘__m256i _mm256_setzero_si256()’: target specific option mismatch
 _mm256_setzero_si256 (void)
 ^
In file included from /home/jarvis/CV/openmvg/include/openMVG/matching/metric.hpp:12:0,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/binary_regions.hpp:16,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/regions_factory.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp:57,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:4:
/home/jarvis/CV/openmvg/include/openMVG/matching/metric_avx2.hpp:54:38: error: called from here
     __m256i dl = _mm256_unpacklo_epi8(d, _mm256_setzero_si256());
                                      ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:43:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Core:269,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Dense:1,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_container.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_io.hpp:12,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx2intrin.h:801:1: error: inlining failed in call to always_inline ‘__m256i _mm256_sub_epi8(__m256i, __m256i)’: target specific option mismatch
 _mm256_sub_epi8 (__m256i __A, __m256i __B)
 ^
In file included from /home/jarvis/CV/openmvg/include/openMVG/matching/metric.hpp:12:0,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/binary_regions.hpp:16,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/regions_factory.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp:57,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:4:
/home/jarvis/CV/openmvg/include/openMVG/matching/metric_avx2.hpp:51:47: error: called from here
     const __m256i d = _mm256_sub_epi8(max, min);
                                               ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:43:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Core:269,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Dense:1,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_container.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_io.hpp:12,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx2intrin.h:370:1: error: inlining failed in call to always_inline ‘__m256i _mm256_max_epu8(__m256i, __m256i)’: target specific option mismatch
 _mm256_max_epu8 (__m256i __A, __m256i __B)
 ^
In file included from /home/jarvis/CV/openmvg/include/openMVG/matching/metric.hpp:12:0,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/binary_regions.hpp:16,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/regions_factory.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp:57,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:4:
/home/jarvis/CV/openmvg/include/openMVG/matching/metric_avx2.hpp:50:53: error: called from here
     const __m256i max = _mm256_max_epu8(ad[i], bd[i]);
                                                     ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:43:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Core:269,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Dense:1,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_container.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_io.hpp:12,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx2intrin.h:412:1: error: inlining failed in call to always_inline ‘__m256i _mm256_min_epu8(__m256i, __m256i)’: target specific option mismatch
 _mm256_min_epu8 (__m256i __A, __m256i __B)
 ^
In file included from /home/jarvis/CV/openmvg/include/openMVG/matching/metric.hpp:12:0,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/binary_regions.hpp:16,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/regions_factory.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp:57,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:4:
/home/jarvis/CV/openmvg/include/openMVG/matching/metric_avx2.hpp:49:53: error: called from here
     const __m256i min = _mm256_min_epu8(ad[i], bd[i]);
                                                     ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:37:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Core:269,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Dense:1,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_container.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_io.hpp:12,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:46:1: error: inlining failed in call to always_inline ‘__m128i _mm_hadd_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_hadd_epi32 (__m128i __X, __m128i __Y)
 ^
In file included from /home/jarvis/CV/openmvg/include/openMVG/matching/metric.hpp:12:0,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/binary_regions.hpp:16,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/regions_factory.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp:57,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:4:
/home/jarvis/CV/openmvg/include/openMVG/matching/metric_avx2.hpp:64:70: error: called from here
   __m128i r = _mm_hadd_epi32(_mm_add_epi32(h, l), _mm_setzero_si128());
                                                                      ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:37:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Core:269,
                 from /home/jarvis/CV/openmvg/include/openMVG/third_party/eigen/Eigen/Dense:1,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_container.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/image/image_io.hpp:12,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:1:
/usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:46:1: error: inlining failed in call to always_inline ‘__m128i _mm_hadd_epi32(__m128i, __m128i)’: target specific option mismatch
 _mm_hadd_epi32 (__m128i __X, __m128i __Y)
 ^
In file included from /home/jarvis/CV/openmvg/include/openMVG/matching/metric.hpp:12:0,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/binary_regions.hpp:16,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/regions_factory.hpp:12,
                 from /home/jarvis/CV/openmvg/include/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp:57,
                 from /home/jarvis/Code/c++/study_mvg/main.cpp:4:
/home/jarvis/CV/openmvg/include/openMVG/matching/metric_avx2.hpp:64:70: error: called from here
   __m128i r = _mm_hadd_epi32(_mm_add_epi32(h, l), _mm_setzero_si128());
                                                                      ^
CMakeFiles/main.dir/build.make:62: recipe for target 'CMakeFiles/main.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/main.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
*** Failure: Exit code 2 ***
```
----------------------------------------------------------------------
This problem has been bothering me for a long time.I hope I can get your help.
thank you very much!
string

**Comment by pmoulon** [comment] 2017-11-11 16:45
Can you please try by using the develop branch this problem must be fixed there?

**Comment by Yannnnnnnnnnnn** [comment] 2017-11-29 04:52
@StringShannon @pmoulon I met the same problem. 
 And it worked after I used the develop branch.

**Comment by pmoulon** [comment] 2018-01-04 05:30
Since @Yannnnnnnnnnnn explained that now the problem is fixed. I'm closing the issue.

**Closed by pmoulon** 2018-01-04 05:30 UTC
