### ISSUE TITLE
Compilation questions, Please help.

### ISSUE THREAD

**Issue by DrslumpLin** [openMVG/openMVG#545] opened 2016-05-01 06:14 UTC
Hellow, would you please give me some advice.

I build the project one by one in Windows, but failed in the "software" part, and the vs2013 give the errors like following:

error 	7	error C2766: Explicit specialization；have defined“bool ARCHIVE::Save<uint32_t>(ARCHIVE::ArchiveSave &,const uint32_t &)”	c:\users\lin\openmvg\src\software\sfm\InterfaceMVS.h	150	1	openMVG_main_openMVG2openMVS

error 	8	error C2766: Explicit specialization；have defined “bool ARCHIVE::Load<uint32_t>(ARCHIVE::ArchiveLoad &,uint32_t &)”	c:\users\lin\openmvg\src\software\sfm\InterfaceMVS.h	150	1	openMVG_main_openMVG2openMVS

**Comment by rperrot** [comment] 2016-05-01 11:15
Is it with the develop or the master branch ?

**Comment by pmoulon** [comment] 2016-05-02 07:41
The error happens on this line: https://github.com/openMVG/openMVG/blob/master/src/software/SfM/InterfaceMVS.h#L150
"ARCHIVE_DEFINE_TYPE(size_t)"

Can you try to include <cstdint>?

@rperrot I think he try to compile in 32 bit since the size_t is interpreted as a uint32_t value.

**Comment by morgand536** [comment] 2016-05-05 01:55
I have the same error when compiling v1.0 in VS2015 in 32 bit.

**Comment by DrslumpLin** [comment] 2016-05-05 16:14
Thank you very much@pmoulon @rperrot . I have find a way to solve the problem. 

Firstly, I have try to include the head #nclide<cstdint> in the head file  "InterfaceMVS.h", then I compile it again ,but it seemed the errors happened agian.

then I add some codes like folllowing 

 #ifndef size_t                                //added code  by Dr.slumpLin 
#	define size_t int                    //added code  by Dr.slumpLin  
#endif                                          ////added code  by Dr.slumpLin  

/*  the ornigal code for marking  the location  of added   code by me (in orther words, the added code  just placed  before  the following code)
// Serialization support for basic types    
ARCHIVE_DEFINE_TYPE(uint32_t)
ARCHIVE_DEFINE_TYPE(size_t)
 the ornigal code for marking  the location  of added   * /

this time no error happped again in build process. But  I have not tested it futher. You can have a try @morgand536.

BTW, I think you gave the right explaination of my compilation errors.Thank you very much @pmoulon

**Comment by rperrot** [comment] 2016-05-06 12:20
I don't think defining size_t is the correct way to deal with this issue. Moreover if you really want to do that, this must be an unsigned integer (the standard required it)

But You should try to include < cstddef > instead of your own inclusion.

**Comment by DrslumpLin** [comment] 2016-05-07 05:28
Thank you @rperrot . Maybe you are right, I will have a try as you told .

**Comment by pmoulon** [comment] 2016-05-10 10:50
@rperrot Including cstddef did not help, since size_t and uint32_t are of the same type on x86 platform... So the compile error is about multiple definition.

What about using that:
```
// Serialization support for basic types
ARCHIVE_DEFINE_TYPE(uint32_t)
ARCHIVE_DEFINE_TYPE(uint64_t) // size_t for x64 platforms
ARCHIVE_DEFINE_TYPE(float)
ARCHIVE_DEFINE_TYPE(double)

```

@DrslumpLin @morgand536  See above for the fix that works for me.

**Comment by rperrot** [comment] 2016-05-10 13:05
@pmoulon Ok. I was mainly saying that defining size_t is not a good idea since it can be found in cstddef. 

Your right in the way you define the standard type for cereal. But I was wondering if the issue is not cereal based not openMVG based ? (ie: way we open an issue in the cereal repo ?)

**Comment by morgand536** [comment] 2016-05-11 00:45
@pmoulon Great! Your code works fine with no error!

**Comment by pmoulon** [comment] 2016-05-11 17:01
@morgand536 @DrslumpLin Thanks for your feedback.
I close the issue, since it is now solved thanks to https://github.com/openMVG/openMVG/commit/9963a66bae826f014482f778d9cfa31bbd0e444a

**Closed by pmoulon** 2016-05-11 17:01 UTC
Labels: build
