### ISSUE TITLE
[OSX][develop] Issue with openMVG2openMVS

### ISSUE THREAD

**Issue by stephane-lb** [openMVG/openMVG#713] opened 2016-12-28 13:26 UTC
Hi Pierre,

Just a quick report during compilation on macOS nothing urgent.

``` 
In file included from /Users/Stephane-lb/Projects/Test_OpenMVG-MVS/openMVG/src/software/SfM/main_openMVG2openMVS.cpp:13:
/Users/Saorel/Projects/Test_OpenMVG-MVS/openMVG/src/software/SfM/InterfaceMVS.h:84:23: error: member reference base type 'unsigned long' is not a structure or union
        const_cast<_Tp&>(obj).serialize(a, 0);
        ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
/Users/Stephane-lb/Projects/Test_OpenMVG-MVS/openMVG/src/software/SfM/InterfaceMVS.h:185:2: note: in instantiation of function template specialization 'ARCHIVE::Save<unsigned long>'
      requested here
        Save(a, size);
        ^
/Users/Stephane-lb/Projects/Test_OpenMVG-MVS/openMVG/src/software/SfM/InterfaceMVS.h:89:5: error: member reference base type 'unsigned long' is not a structure or union
        obj.serialize(a, 0);
        ~~~^~~~~~~~~~
/Users/Stephane-lb/Projects/Test_OpenMVG-MVS/openMVG/src/software/SfM/InterfaceMVS.h:193:2: note: in instantiation of function template specialization 'ARCHIVE::Load<unsigned long>'
      requested here
        Load(a, size);
        ^
2 errors generated.
make[3]: *** [software/SfM/CMakeFiles/openMVG_main_openMVG2openMVS.dir/main_openMVG2openMVS.cpp.o] Error 1
make[2]: *** [software/SfM/CMakeFiles/openMVG_main_openMVG2openMVS.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

At the same time a quick note for SfM_SequentialPipeline.py  and SfM_GlobalPipeline.py [master]

```
# Indicate the openMVG binary directory
OPENMVG_SFM_BIN = "/Users/Saorel/Projects/Test_OpenMVG-MVS/openMVG/_build/Darwin-x86_64-Release/Release"
```
should be replace by : 

```
# Indicate the openMVG binary directory
OPENMVG_SFM_BIN = "/Users/Saorel/Projects/Test_OpenMVG-MVS/openMVG/_build/Darwin-x86_64-Release/"
```

and 

``` 
import commands
```

is not supported in python3

**Comment by pmoulon** [comment] 2016-12-28 17:34
Hi @stephane-lb 

- For your compiler error you can try to comment (I think you have an error seems an existing define have the same size) https://github.com/openMVG/openMVG/blob/829465d6cd66a86bf2fc4002f2f4c47c41f17a77/src/software/SfM/InterfaceMVS.h#L154

Thank you for your comments about the python script.

- Regarding your OPENMVG_SFM_BIN the problem is not as simple as that.
The export path is not the same if you compile using XCode or if you use the native clang.
=> Clang => Darwin-x86_64-Release/
=> XCode => Darwin-x86_64-Release/Release

**Comment by rperrot** [comment] 2017-01-04 08:54
@pmoulon Can you add [OSX] in the title of this issue (just to help search on similar issue).

**Comment by rjanvier** [comment] 2017-01-04 09:01
Maybe we can add some OS related tags for issues. macOS, Linux and Windows.

**Comment by mattmyne** [comment] 2017-01-04 18:33
Just to confirm, uncommenting the line as requested by @pmoulon fixes the (only) compile error using clang on macOS:

"For your compiler error you can try to uncomment https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/InterfaceMVS.h#L154"

Will this change be committed or will it break other OS compiles?

**Comment by stephane-lb** [comment] 2017-01-05 15:31
I will test the new release in the next few days. I will make an update of this post.

I think that if you do not want to affect other compiler you have to uncomment the block.

**Comment by rperrot** [comment] 2017-01-05 15:40
Just to make a precision : theses lines are only intended to fix compilation on clang on OSX. We can not now uncomment for the public repository since it introduce a compilation fail on clang on linux. We know the issue but we  did not find enough time to fix it yet.

**Comment by stephane-lb** [comment] 2017-01-05 15:48
@rperrot in that case why not :

```cpp
#ifdef __APPLE__
  #ifdef TARGET_OS_MAC
    #ifdef __clang__
    ARCHIVE_DEFINE_TYPE(unsigned long)
    #endif
  #endif
#endif
```

Will try it on Mac and Arch asap.

**Comment by rperrot** [comment] 2017-01-05 16:02
We tried something like that and it seems to work, but ideally we would like to alleviate the use of #ifdef / #define in our code for something that is highly system/target dependent. By experience it's really hard to maintain and error prone on system update (if Apple decide to use another branch of the llvm compiler, we may have a new issue to fix). BTW, the best solution is to have standard code with low requirement on compilers.

**Comment by pmoulon** [comment] 2017-01-05 18:14
@mattmyne Thank you for your feedback
In order to improve continuous integration support I would like to work on testing for every commits and PR the continuous integration on osx https://github.com/openMVG/openMVG/issues/722
@stephane-lb keep us update about your test.
The other way would be to check at compilation time if the size of unsigned long is equal to existing two previous definition... but it requires some type traits.

**Comment by pmoulon** [comment] 2017-01-25 21:30
@stephane-lb Any feedback about a potential PR to check the efficiency of
```
#ifdef __APPLE__
  #ifdef TARGET_OS_MAC
    #ifdef __clang__
    ARCHIVE_DEFINE_TYPE(unsigned long)
    #endif
  #endif
#endif
```

**Comment by stephane-lb** [comment] 2017-02-09 11:29
This works on Mac Sierra

```
#ifdef __APPLE__
    #ifdef __clang__
    ARCHIVE_DEFINE_TYPE(unsigned long)
    #endif
#endif
```

**Comment by pmoulon** [comment] 2017-02-10 05:45
Push a fix.
Thank @stephane-lb

**Closed by pmoulon** 2017-02-10 05:45 UTC
Labels: build, enhancement
