### ISSUE TITLE
[sfm] Fix to use BundleAdjustment constraint for control points and a camera model that have empty intrinsic data.

### ISSUE THREAD

**Issue by Joeppie** [openMVG/openMVG#1053] opened 2017-09-13 10:11 UTC
Hello,

We just tried to run a bundle adjustment with the spherical camera model in conjunction with control points.
This caused Ceres to crash with the error `F0912 15:56:42.066993 15748 problem_impl.cc:242] Check failed: parameter_blocks.size() == cost_function->parameter_block_sizes().size() (3 vs. 2) `

I believe this is caused by a lack of checking whether intrinsics are a part of the camera model in `openMVG/sfm/sfm_data_BA_ceres.cpp`

I have not yet checked whether we get useful results with it, but I suggest a change such as this
I suggest the following change in the code at line 404:

```

         if (cost_function)
-          problem.AddResidualBlock(cost_function,
-            nullptr,
-            &map_intrinsics[view->id_intrinsic][0],
-            &map_poses[view->id_pose][0],
-            gcp_landmark_it.second.X.data());
+        {
+          if (!map_intrinsics[view->id_intrinsic].empty())
+          {
+            problem.AddResidualBlock(cost_function,
+                                     nullptr,
+                                     &map_intrinsics[view->id_intrinsic][0],
+                                     &map_poses[view->id_pose][0],
+                                     gcp_landmark_it.second.X.data());
+          }
+          else
+          {
+            problem.AddResidualBlock(cost_function,
+                                     nullptr,
+                                     &map_poses[view->id_pose][0],
+                                     gcp_landmark_it.second.X.data());
+          }
+
+
+
+        }
```

**Comment by Joeppie** [comment] 2017-09-13 11:32
I've just pushed into the fork where we added the Spherical_Equirectangular camera model, the (probable) fix is in this commit: https://github.com/Joeppie/openMVG/commit/3264f1ace9d989d763d9b4dccd7f2de508bc30f1

**Comment by pmoulon** [comment] 2017-09-13 16:56
With this fix did you was able to run BA with the Spherical camera and with the Spherical_Equirectangular?

It would be interesting to understand why it's not working.

**Comment by Joeppie** [comment] 2017-09-13 19:25
>With this fix did you was able to run BA with the Spherical camera and with the Spherical_Equirectangular?

Yes, we have been able to run bundle adjustment succesfully for the Spherical_Equirectangular model.

By the way, before I diagnosed the cause of the problem, I modified the Spherical BA sample to produce a single ControlPoint, and set the OptimizeOptions to use the control points. This is how I reproduced the issue in 'vanilla' OpenMVG code to isolate it. Further investigation led me to conclude there was a difference in how (the absence of) intrinsics are handled between structure and controlpoints when adding the residual blocks to the Ceres problem.

**Comment by pmoulon** [comment] 2017-09-13 19:31
Sorry my question was not clear:
I mean, since you made this fix.
Does the BA is working for the two spherical camera model type?
- Intrinsic_Spherical
- Spherical_Equirectangular 

Btw, I will integrate your change in `openMVG/sfm/sfm_data_BA_ceres.cpp`. Thx.

**Comment by Joeppie** [comment] 2017-09-13 21:14
>Does the BA is working for the two spherical camera model type?
Intrinsic_Spherical
Spherical_Equirectangular

Yes, it worked for both when not having control points. 

It seems to work for Spherical_Equirectangular with control points, and so, it should also work for the Intrinsic_Spherical as well. The common denominator is that they both do not have intrinsic parameters.

By work, I mean; we can see that RMSE for the control points drops when we perform an SFM+BA with just control points, observations, poses and views. (i.e. no structure landmarks)

**Comment by pmoulon** [comment] 2017-09-13 22:10
Did you see a difference in the final RMSE between the two model?
- I mean the Intrinsic_Spherical or Spherical_Equirectangular just use a different way to express spherical coordinates.

Happy you was able to dig into the code and find the cause of the error and share back your finding!

Hoping see you back with new contributions soon ;-)

Let's close this issue when I will have completed the following task:
- [ ] Add support of GCP with Spherical camera for the BA (camera with no intrinsic camera parameter).

**Comment by Joeppie** [comment] 2017-09-14 08:02
>Did you see a difference in the final RMSE between the two model?

Yes, with our (row-column) observations  being correct only for our camera model/mapping, we saw a huge difference in initial RMSE, and consequently an adjustment that did not make sense when I plotted it to shapefiles. This was resolved when using the correct translation to row-column.


>Let's close this issue when I will have completed the following task:
 Add support of GCP with Spherical camera for the BA (camera with no intrinsic camera parameter)

It seems only logical to close the issue when that task has been completed :)

**Comment by pmoulon** [comment] 2017-09-18 22:11
> It seems only logical to close the issue when that task has been completed :)
- that's why I say let close the issue, once I have completed the depicted task "Add support of GCP with Spherical camera for the BA (camera with no intrinsic camera parameter).".

Regarding the two camera model.
I made a test in openMVG_sample_multiview_robustEssential_spherical where I use the two camera model:
- Intrinsic_Spherical or Spherical_Equirectangular. Despite I obtain a similar point cloud, your model is giving larger residual values.
Note: (I remove the log part about the robust estimation that gives exactly the same results)

Here the log when I use the `Intrinsic_Spherical` camera model:
```
$ ./openMVG_sample_multiview_robustEssential_spherical
Compute the relative pose between two spherical image.
...
Bundle Adjustment statistics (approximated RMSE):
 #views: 2
 #poses: 2
 #intrinsics: 1
 #tracks: 14887
 #residuals: 59548
 Initial RMSE: 0.467597
 Final RMSE: 0.06528
 Time (s): 0.516753

Residual statistics (pixels):

	 min: 0.200674
	 mean: 0.71344
	 median: 0.707156
	 max: 1.52417
```

Here the log when I use your `Intrinsic_Spherical_Equirectangular` camera model:
```
$ ./openMVG_sample_multiview_robustEssential_spherical_equi 
Compute the relative pose between two spherical image.
...
Bundle Adjustment statistics (approximated RMSE):
 #views: 2
 #poses: 2
 #intrinsics: 1
 #tracks: 14887
 #residuals: 59548
 Initial RMSE: 53.1632
 Final RMSE: 2.95354
 Time (s): 13.2497

Residual statistics (pixels):

	 min: 0.0320705
	 mean: 361.302
	 median: 294.577
	 max: 1148.86
```

Notice the Bundle adjustment is slower with your camera model.
Notice the residual statistics are higher in your camera model.

Did you encounter the same behavior in your case (Replace `Intrinsic_Spherical` by `Intrinsic_Spherical_Equirectangular` here https://github.com/Joeppie/openMVG/blob/master/src/openMVG_Samples/multiview_robust_essential_spherical/robust_essential_spherical.cpp#L79)?

**Comment by Joeppie** [comment] 2017-09-19 06:15
Hello Pierre,

I discovered friday, and yesterday was working on resolving the issue that in our spherical 'equirectangular'model, if we have coordinates on a 4800,2400 that result in residual the following situation should have an error of 2 px:

    x = {4799,1200} proj = {1,1200}

What is happening in the code, as it is currently still checked in is simply x-proj ==> {4797,0}
In our cylindrical projection of course, the distance should be measured as being 2 pixels.

I may have a checkin ready that resolves this tomorrow, but unfortunately I am not in the office today.
Resolution is to properly implement the (fortunately virtual) residual method so that it wraps around the cylinder calculating the residuals :)

**Comment by pmoulon** [comment] 2017-09-20 02:31
@Joeppie:
- The fix for the BA constraint with a GCP and a camera model that does not have intrinsic data is merged.
- Now if you try to use a camera model that have not been registered in IntrinsicsToCostFunction(...) the BA will fail and a error message is displayed. It will make any update more easy ;-)

- Waiting your fix for to handle the circular constraint along X ;-)
  - Does the same problem can happen in the Y direction?

**Comment by Joeppie** [comment] 2017-09-20 13:14
Hey Pierre,

>Does the same problem can happen in the Y direction?
Not with our equirectangular images, covering 360 degrees on x (causing the situation) and 180 on Y.

Also, I was wondering if there should perhaps be some sort of test code that should be present which verifies the functor returns the same residual as the implementation would;
I think that the existing spherical model returns proj -x as residual , but the does functor x- proj? That may not be much of an issue, but it if I interpreted that correctly, it is rather silly.

I determined this when I figured out my wrapping was incorrect (in the functor) and leading to weird RMSE as determined by Ceres.

**Comment by pmoulon** [comment] 2017-09-20 15:51
You're right it could be better if we sync the two implementation to always do the same.
BTW, most of the time the SquaredNorm or the Norm of this residual vector is considered and so the same value will be computed.
After I think using (x-proj) or (proj-x) is just a convention choice.

At least this thing helps you to discover a bug in your implementation, so the drawback got was good ;-)

**Comment by pmoulon** [comment] 2017-11-17 16:29
@Joeppie I'm closing the issue since the Issue Title have been solved."[sfm] Fix to use BundleAdjustment constraint for control points and a camera model that have empty intrinsic data."

Hoping to see you back with other contribution and feel free to repopen a new issue is needed!

Note: This issue can also interest you https://github.com/openMVG/openMVG/issues/1133 since it will bring support of spherical images for Incremental SfM!

**Closed by pmoulon** 2017-11-17 16:29 UTC
Labels: enhancement
