### ISSUE TITLE
Why just three points in colorized.ply after run ./openMVG_main_ComputeSfM_DataColor ?

### ISSUE THREAD

**Issue by wguo68** [openMVG/openMVG#806] opened 2017-02-24 15:00 UTC
ply
format ascii 1.0
element vertex 3
property double x
property double y
property double z
property uchar red
property uchar green
property uchar blue
end_header
0.1147002857987577 0.1876564172006815 1.1484053648106540 254 254 254
0.0977171049577899 0.1973562738289988 1.1077931079317538 0 255 0
0.1039811158069835 0.2056427565451712 1.0839441654724284 0 255 0

**Comment by rjanvier** [comment] 2017-02-24 15:06
It's not normal. Have you got the same amount of point in your cloud_and_poses.ply file?

**Comment by rperrot** [comment] 2017-02-24 15:40
How many images are you using ? what are their resolution ? what pipeline did you use ? 

This may be caused by a insuffisant coverage between images or two blurry images.

**Comment by wguo68** [comment] 2017-02-24 23:19
I used 16 imaqges and image size is 640*480. I use the pipeline as the document said.
This is the cloud_and_poses.ply: 
ply
format ascii 1.0
element vertex 3
property double x
property double y
property double z
property uchar red
property uchar green
property uchar blue
end_header
0.0977171049577899 0.1973562738289988 1.1077931079317538 0 255 0
0.1039811158069835 0.2056427565451712 1.0839441654724284 0 255 0
0.1147002857987577 0.1876564172006815 1.1484053648106540 255 255 255

**Comment by pmoulon** [comment] 2017-02-24 23:35
Since you are using images with no so much texture (faces), you will have to tweak the parameter to ask OpenMVG to detect more features per images (as @rperrot said to you you have some parameter to do that => ComputeMatches -p HIGH)

**Comment by billy-antoine** [comment] 2017-03-10 13:04
Hi,

I have the same issue, even with **ComputeFeatures -p HIGH**, the generated sfm_data_color.ply is vertexless...

**Comment by rperrot** [comment] 2017-03-10 13:22
This may be an issue with the dataset itself. If it's possible, could you share us your set (to see by eye if there's enough texture, enough coverage between images, static objects).

**Comment by billy-antoine** [comment] 2017-03-10 13:42
Here are the used pictures :
![image](https://cloud.githubusercontent.com/assets/14361230/23797282/6ba7fdf2-059f-11e7-9a12-fb1e0e124425.png)

The point cloud generation works perfectly, as we can see here :
![image](https://cloud.githubusercontent.com/assets/14361230/23797308/8b476a80-059f-11e7-8e43-89dde78276fe.png)

But the sfm_data_color.ply is still empty :(

**Comment by rperrot** [comment] 2017-03-10 13:44
you mean the colorize.ply or the robust_colorized.ply ?

**Comment by billy-antoine** [comment] 2017-03-10 13:50
Okay, I think we are going to where my mistake is...
I only used **openMVG_main_ComputeSfM_DataColor** in order to build the colored points cloud, following the SfM pipeline from the given dorumentation.

**Comment by rperrot** [comment] 2017-03-10 13:53
The easiest use of openMVG is to use (directly or slightly modified) the proposed pipelines. It does everything and if inputs images are OK it works like a charm.

**Comment by pmoulon** [comment] 2017-03-10 23:45
@billy-antoine Can you close the issue since the solution to your problem was found.
You was using the wrong tool.

For faces, the best results we have obtained is often by setting the detector to HIGH.
Sometimes using AKAZE_FLOAT and the ANNL2 matcher allow to have better results (at a higher computation time).

**Comment by billy-antoine** [comment] 2017-03-13 13:17
Yes, thank you, 
But I am afraid I can't close the issue as i am not the one who opened it.
I hope it helped @wguo68 though :)

**Comment by pmoulon** [comment] 2017-03-13 19:35
@wguo68 Can you close the issue if your problem is solved?

@billy-antoine Thank you, I made a mistake on the issue creator ;-)

**Comment by pmoulon** [comment] 2017-03-16 02:39
Closed due to inactivity by the issue opener.

**Closed by pmoulon** 2017-03-16 02:39 UTC
