### ISSUE TITLE
Build error with clang-6

### ISSUE THREAD

**Issue by yurivict** [openMVG/openMVG#1275] opened 2018-04-06 17:41 UTC
Getting this on FreeBSD:
```
/usr/ports/misc/openmvg/work/openMVG-1.3/src/dependencies/osi_clp/Clp/src/ClpModel.cpp: In member function 'int ClpModel::writeMps(const char*, int, int, double) const':
/usr/ports/misc/openmvg/work/openMVG-1.3/src/dependencies/osi_clp/Clp/src/ClpModel.cpp:3848:59: error: invalid cast from type 'std::nullptr_t' to type 'const char*'
                        reinterpret_cast<const char*> (NULL) /*integrality*/,
                                                           ^
```

Could you please make sure it builds with clang6? I would like to create the FreeBSD port, and for this it needs to build with clang.

**Comment by pmoulon** [comment] 2018-04-06 17:44
Sure, do you have a working fix for this?

**Comment by yurivict** [comment] 2018-04-06 17:45
> Sure, do you have a working fix for this?

Me? No.

**Comment by jbeich** [comment] 2018-04-09 10:38
Caused by freebsd/freebsd@c8ed04c26b67 because Clang 6 defaults to C++11. To fix the error either drop `reinterpret_cast` or use `static_cast`.

**Comment by pmoulon** [comment] 2018-04-10 03:17
Thx @jbeich I will have a look to it.

**Comment by yurivict** [comment] 2018-04-10 03:52
Does this mean that simply setting ```-std=c++11``` should help?

**Comment by DimitryAndric** [comment] 2018-04-10 12:39
Yes, that could also help.  Getting rid of the cast would be better, but it looks like external third-party source?

**Comment by yurivict** [comment] 2018-04-10 15:30
clang crashes on this project when I've set this flag.

**Comment by DimitryAndric** [comment] 2018-04-10 15:59
Hm, it looks like that crash is totally unrelated to this casting issue though.  Can you try to get rid of all the -mno-sse options, and see if that fixes it?

**Comment by yurivict** [comment] 2018-04-10 17:47
After removing all -mno-sseN it still fails for yet another reason: https://github.com/openMVG/openMVG/issues/1281

**Closed** 2019-07-19 00:01 UTC
Labels: bug, build, help_wanted

**Comment by yurivict** [comment] 2020-03-01 20:26
This compiler bug is still reproducible: https://bugs.llvm.org/show_bug.cgi?id=37067#c2

**Comment by pmoulon** [comment] 2020-03-02 17:39
Thx for the update. Happy to see that the community is trying to understand what's going on on CLANG-6

**Comment by DimitryAndric** [comment] 2020-05-23 17:07
The upstream bug was a duplicate of https://bugs.llvm.org/show_bug.cgi?id=30426. That bug is also still open, as the cause is known, but apparently a solution has not been agreed upon.

In any case, the problem occurs because the build targets x86_64, while also forcibly disabling SSE, and then tries to return a double. This is not possible in the x86_64 ABI, as you have to use an SSE register for this. It should actually just give you a compilation error similar to what gcc does, e.g. "SSE register return with SSE disabled".

If at all possible, I would try disabling only SSE2 and higher, not SSE.
