### ISSUE TITLE
tutorial_demo.py fails?

### ISSUE THREAD

**Issue by darinkgrant** [openMVG/openMVG#293] opened 2015-05-12 22:11 UTC
I believe I have compiled everything correctly for Mac OSX but part way through the tutorial demo it fails with:

Triangulation took (s): 0.003
solver.cc:484 Terminating: Invalid configuration. Solver::Options::num_threads = 0. Violated constraint: Solver::Options::num_threads > 0
Bundle Adjustment failed.
Outlier removal (remaining #points):
	 initial structure size #3DPoints: 2475
		 pixel residual filter  #3DPoints: 463
		 angular filter         #3DPoints: 463
GlobalSfM:: Non-linear adjustment failure!
5. Colorize Structure

The input SfM_Data file "[...]/openMVG_Build/software/SfM/tutorial_out/reconstruction_global/sfm_data.json" cannot be read.

Any ideas why?  I can't trace back the call to Solver::Solve easily to understand why a non-zero threadcount isn't passed through (I tried compiling both vanilla and with threads=8).

**Comment by pmoulon** [comment] 2015-05-13 07:00
Hi @darinkgrant 

The problem seems located in the BA library (OpenMVG use Ceres solver to perform this task).
I think that the wrong number of thread is send to Ceres API in openMVG.

Since clang does not support openMP thread, perhaps there is a tiny error here:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_data_BA_ceres.cpp#L43
Can you print the _nbThreads value on line 44?
```
std::cout << "#threads for BA " << _nbThreads << std::endl;
```
If the value is not set correctly, set it to 1 (and rerun the compilation and tutorial).
If it solves the problem, please say it to me, and we must patch openMVG.

If the problem persists we must check unit test results to see where the problem is hidden.
Can you try to enable test builds, run them and share the resulting report?
 $ cmake -DCMAKE_BUILD_TYPE=RELEASE -DOpenMVG_BUILD_TESTS=ON -DOpenMVG_BUILD_EXAMPLES=ON -G "Xcode" . ../openMVG/src/
 $ xcodebuild -configuration Release
$ make test

**Comment by darinkgrant** [comment] 2015-05-13 12:37
Hi @pmoulon,

#Threads for BA 0

and, indeed, because of the check for multithreadedness in line 42 it was never set properly.  Setting it to 1 allows the demo to complete and given that there isn't support for openMP, it suggests that this section should always be set to single threaded, right?

**Comment by pmoulon** [comment] 2015-05-13 12:44
Thanks for your time and your answer
You're right, ceres is also using OpenMP for threading, so only one thread for BA will be used.
I will fix that issue "forgotten default initialization to 1" today.

**Comment by pmoulon** [comment] 2015-05-13 13:21
Must be fixed by the last commit!
:+1:

**Closed by pmoulon** 2015-05-13 13:21 UTC

**Comment by darinkgrant** [comment] 2015-05-13 15:05
@pmoulon Thank you!
