### ISSUE TITLE
How to use 

### ISSUE THREAD

**Issue by bigakoz** [openMVG/openMVG#779] opened 2017-02-10 12:25 UTC
Hi,

I have downloaded openGV and ran CMake for VisualStudio 2015.

When compiling I was getting
"Command line error D8021: invalid numeric argument '/Wextra'"

I changed the following command line option from
 /bigobj -Wextra -Wwrite-strings -Wno-unused-parameter -fno-strict-aliasing 

to 
 /bigobj

and it compiles.

is this Ok or will this create some problems elsewhere ?

Regards,

Alan

**Comment by rperrot** [comment] 2017-02-10 14:26
At a first, this only concern compilation warnings (but the -fno-strict-aliasing may have an influence on the generated code, try to keep it if possible). 

But we may need to understand why it doesn't compile on your version (vs 2015 is known to compile fine without changing anything). 

Can you tell us some informations about your environment : 
- Windows version ? (32/64 bits ?)
- cmake version ? (maybe if it's outdated, it could generate a bad VS project file)
- visual studio version ? (community, pro ? with or without release pack ?)

Thanks in advance.

**Comment by pmoulon** [comment] 2017-02-10 15:27
Alan, it will not create problem.

BTW, I would advise you to use my FORK and this branch:
https://github.com/pmoulon/opengv/tree/develop_boostless

I made some minor changes that ease compilation and setup of the library.

**Comment by pmoulon** [comment] 2017-02-10 15:31
Closing since it is a duplicate of https://github.com/openMVG/openMVG/issues/777

**Closed by pmoulon** 2017-02-10 15:31 UTC

**Comment by bigakoz** [comment] 2017-02-11 12:16
Hi,

I am using
1. CMake 3.7.1
2. CMake compiler selection   - Visual Studio 14 2015 win64 (use default native compilers)
3. Visual Studio Community 2015 (the free version)

When I google the compiler error I found a suggestion to include this:

# Set default compile flags for GCC
if(CMAKE_COMPILER_IS_GNUCXX)
    message(STATUS "GCC detected, adding compile flags")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++98 -pedantic -Wall -Wextra")
endif(CMAKE_COMPILER_IS_GNUCXX)

I am not proficient with CMake but added the above lines but it didn't make any difference

**Comment by rperrot** [comment] 2017-02-11 12:27
"I am not proficient with CMake but added the above lines but it didn't make any difference"

That absolutely normal. The statements above do something when your compiler is gcc, but your compiler is vc so it does not change anything on your platform. 

Thanks for giving us your platform details, we need to investigate to understand why it does not compile on your platform. 

Is openMVG compiled standalone or included inside another project ?

**Comment by bigakoz** [comment] 2017-02-11 12:42
openMVG is compiled standalone.

I also just realized that I probably need to download openMVG from the 'develop_subposes' directory rather than the master library. I would assume it is a dependency of openMVG in the devlop_subposes version.

I was compiling openGV as a standalone compilation so maybe that was my mistake.

I have only just started using openMVG so not that proficient with it yet.

As an aside. i don't quite understand what openGV actually does ?
- Does it solve each rigid pose (for say three cameras) independently and the mergen it back into the SFM pipeline ?
or
- Adds the rigid pose as an extra constraint in the SFM bundle adjustement ?

Does the relative pose between cameras need to be known 'a priori' or is solved assuming a reasonable estimate is supplied ?

**Comment by pmoulon** [comment] 2017-02-12 04:03
openGV is a library to compute relative or absolute pose for single or multiple camera.
It is used in the branch develop_subposes to compute the relative poses of rigid cluster of cameras.

So when you have a multicamera system in OpenMVG, it must be calibrated in advance. Then you use this calibration and send it to the pipeline. The rigid poses are used in blocks and relative poses are computed and then merged.

The rigid poses are not a direct extra constraint in the SfM bundle adjustment, but then can be relaxed (minimized/refined) if the user ask it.

So to conclude, yes the relative pose between the camera must be known in advance.
We can work on a tool to calibrate the rig if you need to.

**Comment by bigakoz** [comment] 2017-02-12 11:21
Thanks Pierre,

Have just managed to compile the new version so will have a play and see how it works.

Some of the data I have comprises three cameras on a ROV. The imagery is time tagged so I can create image pairs (or triplets) for camera exposure.

However some of the data will have unknown relative orientation between the central camera and the other cameras. So i was it would be able to solve the relative poses.

Anyway I will try and work how this works and see how I go.

My understanding is only need to edit the sfm_data.json file for this pipeline to work.
