### ISSUE TITLE
openMVG error C3861: '__popcnt64': identifier not found

### ISSUE THREAD

**Issue by ravi45** [openMVG/openMVG#365] opened 2015-08-18 06:32 UTC
i am using visual studio 2013. i got this error in 

C3861: '__popcnt64': identifier not found	C:\Users\admin\openMVG\src\openMVG\matching\metric_hamming.hpp	86	1	openMVG_main_computeMatchesCasHas 

please help . how to solve this

**Comment by pmoulon** [comment] 2015-08-18 07:39
Hi @ravi45 
According the msdn documentation you should be able to use __popcnt64 https://msdn.microsoft.com/en-us/library/bb385231(v=vs.120).aspx

Can you tell me:
Do you have a 64bit CPU?
Do you try to build in 64bits?

**Comment by ravi45** [comment] 2015-08-18 07:41
no i have 32bit .

**Comment by ravi45** [comment] 2015-08-18 07:44
any solution for that please..

**Comment by pmoulon** [comment] 2015-08-18 07:45
Do you compile master or develop?

For a try you can comment l141 to l159 and comment also line 166.
So you will have something like
```
/*
#ifdef PLATFORM_64_BIT
    if(size%64 == 0)
    {
      const uint64_t* pa = reinterpret_cast<const uint64_t*>(a);
      const uint64_t* pb = reinterpret_cast<const uint64_t*>(b);
      size /= (sizeof(uint64_t)/sizeof(unsigned char));
      for(size_t i = 0; i < size; ++i, ++pa, ++pb ) {
        result += popcnt64(*pa ^ *pb);
      }
    }
    else
    {
      const uint32_t* pa = reinterpret_cast<const uint32_t*>(a);
      const uint32_t* pb = reinterpret_cast<const uint32_t*>(b);
      size /= (sizeof(uint32_t)/sizeof(unsigned char));
      for(size_t i = 0; i < size; ++i, ++pa, ++pb ) {
        result += popcnt32(*pa ^ *pb);
      }
    }
#else
*/
    const uint32_t* pa = reinterpret_cast<const uint32_t*>(a);
    const uint32_t* pb = reinterpret_cast<const uint32_t*>(b);
    size /= (sizeof(uint32_t)/sizeof(unsigned char));
    for(size_t i = 0; i < size; ++i, ++pa, ++pb ) {
      result += popcnt32(*pa ^ *pb);
    }
//#endif
    return result;
```

**Comment by ravi45** [comment] 2015-08-18 07:47
i will try this . thanks

**Comment by ravi45** [comment] 2015-08-18 08:39
commented these code 

/*
#ifdef PLATFORM_64_BIT
    if(size%64 == 0)
    {
      const uint64_t* pa = reinterpret_cast<const uint64_t*>(a);
      const uint64_t* pb = reinterpret_cast<const uint64_t*>(b);
      size /= (sizeof(uint64_t)/sizeof(unsigned char));
      for(size_t i = 0; i < size; ++i, ++pa, ++pb ) {
        result += popcnt64(*pa ^ *pb);
      }
    }
    else
    {
      const uint32_t* pa = reinterpret_cast<const uint32_t*>(a);
      const uint32_t* pb = reinterpret_cast<const uint32_t*>(b);
      size /= (sizeof(uint32_t)/sizeof(unsigned char));
      for(size_t i = 0; i < size; ++i, ++pa, ++pb ) {
        result += popcnt32(*pa ^ *pb);
      }
    }
#else */
    const uint32_t* pa = reinterpret_cast<const uint32_t*>(a);
    const uint32_t* pb = reinterpret_cast<const uint32_t*>(b);
    size /= (sizeof(uint32_t)/sizeof(unsigned char));
    for(size_t i = 0; i < size; ++i, ++pa, ++pb ) {
      result += popcnt32(*pa ^ *pb);
    }
//#endif
    return result;

still that error is not solved.

**Comment by pmoulon** [comment] 2015-08-18 08:42
Ok, it's because popcount64 is still used in a function.

Can you do the following on popcnt64 function?
```
static inline unsigned int popcnt64(uint64_t n)
  {
/*#ifdef _MSC_VER
    return __popcnt64(n);
#else
#if (defined __GNUC__ || defined __clang__) && defined USE_SSE
    return __builtin_popcountll(n);
#endif*/
    n -= ((n >> 1) & 0x5555555555555555LL);
    n = (n & 0x3333333333333333LL) + ((n >> 2) & 0x3333333333333333LL);
    return (((n + (n >> 4))& 0x0f0f0f0f0f0f0f0fLL)* 0x0101010101010101LL) >> 56;
//#endif
  }
```

**Comment by ravi45** [comment] 2015-08-18 09:18
it works.
Thank you very much.

**Comment by ravi45** [comment] 2015-08-18 10:00
now it's generating " The system can not find the file specified " can you please help me in this  ??

**Comment by pmoulon** [comment] 2015-08-18 10:08
Can you provide more information?
-compilation error log... runtime...

**Comment by ravi45** [comment] 2015-08-19 04:34
this is some last lines of log and in image error i got ..
![error 2](https://cloud.githubusercontent.com/assets/13846199/9348801/b36bc300-4659-11e5-854d-b345d35b5888.png)
![error open mvg](https://cloud.githubusercontent.com/assets/13846199/9348802/b36e83d8-4659-11e5-8b76-8dcf7da7b093.png)



"  Creating library D:/try/software/SfM/Release/openMVG_main_ComputeStructureFromKnownPoses.lib and object D:/try/software/SfM/Release/openMVG_main_ComputeStructureFromKnownPoses.exp
62>  openMVG_main_ComputeStructureFromKnownPoses.vcxproj -> D:\try\software\SfM\Release\openMVG_main_ComputeStructureFromKnownPoses.exe
63>------ Build started: Project: ALL_BUILD, Configuration: Release Win32 ------
63>  Building Custom Rule C:/Users/admin/openMVG/src/CMakeLists.txt
63>  CMake does not need to re-run because D:\try\CMakeFiles\generate.stamp is up-to-date.
========== Build: 63 succeeded, 0 failed, 0 up-to-date, 0 skipped =========="

**Comment by pmoulon** [comment] 2015-08-19 07:20
Please notice that you are in Debug mode.
When you run the selected target (ALL_BUILD) there is no binary, so the displayed message is "unable to start program"

To select a binary target (i.e. a binary target in OpenMVG/software). Go in the Solution explorer and
1. Right-click a project's target name.
2. From the context menu, select Set as Startup Project.
3. The selected startup project's name now appears in bold.

**Comment by ravi45** [comment] 2015-08-19 08:17
i have selected Set as startup project and it display some option like this . what should i do now ?
![f](https://cloud.githubusercontent.com/assets/13846199/9351629/d0a77d32-4678-11e5-877d-54d406a3bb35.png)

**Comment by ravi45** [comment] 2015-08-19 09:42
please replay ..

**Comment by pmoulon** [comment] 2015-08-19 09:58
First:
- all the libraries and openMVG binaries have been well build.

So please explain what you want to do.

If you want use the openMVG SfM pipelines, open your build directory and try one of the python script located in openMVG_Build/software/SfM
```
$ python tutorial_demo.py
```
or
```
$ python SfM_SequentialPipeline.py YourImageDir YourOutputDir
```
Documentation related to SfM is here:
http://openmvg.readthedocs.org/en/latest/software/SfM/SfM/

**Comment by ravi45** [comment] 2015-08-19 10:06
i want to run openMVG in my visual studio so i can understand it . after that i can change it in my way . is it possible or not ??

**Comment by pmoulon** [comment] 2015-08-19 10:16
Yes, select the target your need to launch:
to launch the example openMVG_main_SfMInit_ImageListing target, please do the following:
- double click on OpenMVG in the solution explorer
- double click on software
- right click on the target called openMVG_main_SfMInit_ImageListing, do right click "Set as startup target"

![unnamed](https://cloud.githubusercontent.com/assets/3235050/9353854/f35d875c-466b-11e5-949b-a73708e9a0e4.jpg)

**Comment by ravi45** [comment] 2015-08-19 10:22
after doing that it shows me this in log .

"openMVG_main_SfMInit_ImageListing.exe' (Win32): Loaded 'C:\Windows\System32\msctf.dll'. Cannot find or open the PDB file.
First-chance exception at 0x75A6B760 in openMVG_main_SfMInit_ImageListing.exe: Microsoft C++ exception: std::basic_string<char,std::char_traits<char>,std::allocator<char> > at memory location 0x002CFD0C.
The program '[2124] openMVG_main_SfMInit_ImageListing.exe' has exited with code 1 (0x1).
"

**Comment by pmoulon** [comment] 2015-08-19 10:28
If you want to run a binary with visual studio you must be in Debug or RelWithDebugInfo compilation mode.You are here in release

**Comment by ravi45** [comment] 2015-08-19 10:32
same log hear after changing to debug mode 
"'openMVG_main_SfMInit_ImageListing.exe' (Win32): Loaded 'C:\Windows\System32\msctf.dll'. Cannot find or open the PDB file.
First-chance exception at 0x75A6B760 in openMVG_main_SfMInit_ImageListing.exe: Microsoft C++ exception: std::basic_string<char,std::char_traits<char>,std::allocator<char> > at memory location 0x0027FC28.
The program '[848] openMVG_main_SfMInit_ImageListing.exe' has exited with code 1 (0x1).
"

**Comment by ravi45** [comment] 2015-08-19 11:05
i can't understand what i am doing wrong.

**Comment by pmoulon** [comment] 2015-08-19 11:28
Can you compile in 64bits?

**Comment by ravi45** [comment] 2015-08-19 11:38
yes. in 64bits should i compile in debug mode of release mode ?

**Comment by pmoulon** [comment] 2015-08-19 11:57
So, I have checked, there is no problem in 32 bits. It's only an output message once the program is finished (not a bug).
Put some breakpoint in the code and you will see that all the steps run fine.
I recommend to use 64 bits, it allows a better memory alignment.
The PDB file is because windows lib have no debug information.

**Comment by ravi45** [comment] 2015-08-20 04:42
after successful compilation  , what output it will display ?

**Comment by pmoulon** [comment] 2015-08-20 07:28
Please continue the dicussion on openmvg-team[AT]googlegroups.com
If you launch openMVG_main_SfMInit_ImageListing.exe in a windows cmd windows it will output:
```
$ openMVG_main_SfMInit_ImageListing.exe 
Usage: ./openMVG_main_SfMInit_ImageListing
[-i|--imageDirectory]
[-d|--sensorWidthDatabase]
[-o|--outputDirectory]
[-f|--focal] (pixels)
[-k|--intrinsics] Kmatrix: "f;0;ppx;0;f;ppy;0;0;1"
[-c|--camera_model] Camera model type:
	 1: Pinhole
	 2: Pinhole radial 1
	 3: Pinhole radial 3 (default)
[-g|--group_camera_model]
	 0-> each view have it's own camera intrinsic parameters,
	 1-> (default) view can share some camera intrinsic parameters

Invalid command line parameter.
```

**Comment by ravi45** [comment] 2015-08-20 07:29
ok. 
Thank you very much .

**Comment by pmoulon** [comment] 2015-08-21 15:06
I close the issue since the compilation have been solved.
Thanks for your feedback.

**Closed by pmoulon** 2015-08-21 15:06 UTC
Labels: build
