### ISSUE TITLE
hello，does anybody tell me how exactly install openmvg on win64 vs2015，i had try many ways but did not work

### ISSUE THREAD

**Issue by seuwanglang** [openMVG/openMVG#1859] opened 2021-02-21 08:26 UTC

**Comment by pmoulon** [comment] 2021-02-21 16:50
Duplicate of https://github.com/openMVG/openMVG/issues/1856
Can you share your cmake and VS studio log there?

**Comment by pmoulon** [comment] 2021-02-21 17:00
If you need an existing OpenMVG version, there is a pre-compiled version ready to use here https://github.com/openMVG/openMVG/releases/tag/v1.6

**Comment by seuwanglang** [comment] 2021-02-24 07:38
@pmoulon thank you so much, i have already solve the problems.

**Comment by pmoulon** [comment] 2021-02-25 06:00
I will so close both issues

**Closed by pmoulon** 2021-02-25 06:00 UTC
